In [1]:
import tensorflow as tf
import numpy as np

In [3]:
inputs = np.random.random([32, 10, 8]).astype(np.float32) #[batch, timesteps, feature]
simple_rnn = tf.keras.layers.SimpleRNN(4) #vector hiddenstate dimension 4

output = simple_rnn(inputs)  # The output has shape `[32, 4]`.

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)

In [12]:
final_state

<tf.Tensor: shape=(32, 4), dtype=float32, numpy=
array([[ 0.93690854,  0.6146919 ,  0.8546216 , -0.30172756],
       [ 0.25319186, -0.5147727 ,  0.76726186, -0.7067347 ],
       [ 0.75911313, -0.8765107 ,  0.8193046 , -0.5521642 ],
       [ 0.9179154 , -0.3317804 ,  0.75875723, -0.7594445 ],
       [ 0.8229867 , -0.03933562,  0.7770844 , -0.6783605 ],
       [ 0.9750405 , -0.12753958,  0.44718954, -0.0568545 ],
       [ 0.79678625,  0.17967801,  0.89300394, -0.59241664],
       [ 0.9322466 , -0.14319092,  0.75558484, -0.29717752],
       [ 0.81648445, -0.6657647 ,  0.83413064, -0.72638464],
       [ 0.93665147,  0.585959  ,  0.886692  ,  0.132833  ],
       [ 0.8942023 ,  0.41117457,  0.8631669 , -0.18329233],
       [ 0.7304065 , -0.5183556 ,  0.84853727, -0.60263944],
       [ 0.91170144,  0.36245885, -0.4228938 , -0.8843282 ],
       [ 0.6119555 , -0.48465988,  0.80363774, -0.639348  ],
       [ 0.8333077 , -0.5170682 ,  0.7764074 , -0.33672732],
       [ 0.87766385,  0.3894845 ,  0

In [25]:
weights = simple_rnn.get_weights()
for i in weights:
    print(i.shape)
# (8, 4) wax
# (4, 4) waa
# (4,) way

(8, 4)
(4, 4)
(4,)


In [31]:
parameters = {}
keras_Wax = weights[0] #lay weights tu` keras
keras_Waa = weights[1] #lay weights tu` keras
keras_Way = weights[2] #lay weights tu` keras
parameters['Waa'] = keras_Waa
parameters['Wax'] = keras_Wax
parameters['Way'] = keras_Way
print(keras_Wax.shape)
print(keras_Waa.shape)
print(keras_Way.shape)
print(keras_Wax)
print(keras_Waa) 
print(keras_Way) #way = 0 ##interesting

(8, 4)
(4, 4)
(4,)
[[ 0.6171467   0.29153597  0.2561109   0.1801095 ]
 [ 0.5615799   0.23985416 -0.648728   -0.26105016]
 [ 0.6029144   0.6673818  -0.11119133 -0.03903353]
 [-0.24229565  0.33146435  0.28393203  0.2222184 ]
 [ 0.41002458  0.5501165   0.07717288  0.12989742]
 [-0.03963858 -0.54967546  0.33611542 -0.58931476]
 [-0.46924818 -0.15948027  0.26155     0.11409372]
 [ 0.24006271 -0.46091288  0.51203936  0.6519672 ]]
[[ 0.8150269  -0.32981598  0.46676406 -0.0953087 ]
 [-0.437179   -0.29407734  0.66392684  0.5306544 ]
 [-0.34144998  0.02880062  0.44794577 -0.8257887 ]
 [ 0.1673842   0.8966105   0.37506923  0.16551487]]
[0. 0. 0. 0.]


In [17]:
def mysm(x):
    return np.exp(x)/sum(np.exp(x))

In [27]:
def my_rnn_cell(previous_a, x, parameters):
    Waa = parameters['Waa']
    Wax = parameters['Wax']
    Way = parameters['Way']
    #print('test',keras_Wax.shape)
    #print('test',keras_Waa.shape)
    #print('test',keras_Way.shape)
    #ba = parameters['ba']
    #by = parameters['by']
    temp_a = np.dot(x,Wax) # (32, 8) * (8, 4)  =(32, 4) 
    temp_b = np.dot(previous_a, Waa) # (32,4) *  (4, 4) = (32, 4)
    hiddenstate = np.tanh( temp_a+temp_b  )#+ ba)
    y = mysm(np.dot(hiddenstate,Way))#+ by)
    return hiddenstate, y

def rnn_foward(inp):
    timestep = 10
    a_prev = np.zeros((32,4))
    for t in range(timestep):
        #print(a_prev.shape)
        #print(inp[:,t,:].shape)
        t_hiddenstate, t_y = my_rnn_cell(a_prev, inp[:,t,:], parameters)
        #print(t_hiddenstate.shape)
        a_prev = t_hiddenstate    
    print(t_hiddenstate) #state cuoi cung

In [28]:
rnn_foward(inputs)

[[ 0.93690852  0.61469192  0.85462156 -0.30172753]
 [ 0.25319193 -0.51477268  0.76726178 -0.70673476]
 [ 0.75911316 -0.87651069  0.81930466 -0.55216416]
 [ 0.91791543 -0.33178043  0.75875719 -0.75944445]
 [ 0.82298671 -0.03933559  0.77708433 -0.6783605 ]
 [ 0.97504062 -0.12753968  0.4471895  -0.05685454]
 [ 0.79678623  0.1796781   0.89300388 -0.59241666]
 [ 0.93224659 -0.14319093  0.75558476 -0.29717756]
 [ 0.8164844  -0.6657647   0.83413069 -0.72638456]
 [ 0.93665143  0.58595899  0.886692    0.13283307]
 [ 0.8942023   0.41117461  0.86316705 -0.18329229]
 [ 0.73040648 -0.51835564  0.84853727 -0.60263935]
 [ 0.91170153  0.36245882 -0.42289373 -0.88432805]
 [ 0.61195542 -0.4846598   0.80363763 -0.63934788]
 [ 0.83330763 -0.51706818  0.77640742 -0.3367272 ]
 [ 0.87766383  0.3894846   0.77372214 -0.76914784]
 [ 0.8979305   0.30427496  0.26062991 -0.43691072]
 [ 0.89210396 -0.22660277  0.91210914 -0.55624297]
 [ 0.90739691 -0.19254784  0.42541409 -0.80882852]
 [ 0.87389408 -0.44601914  0.80

In [29]:
###BACKWARD###